[package]
name = "airbox"
version = "0.0.4"
description = "AirBox - 手机电脑局域网互传文件"
authors = ["clanzhang"]
edition = "2021"
rust-version = "1.77.2"

[lib]
name = "airbox_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
axum = { version = "0.7", features = ["multipart", "ws"] }
tauri-plugin-notification = "2"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["io"] }
futures-util = "0.3"
tower = "0.5"
tower-http = { version = "0.5", features = ["cors"] }
http-body-util = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rand = "0.8"
if-addrs = "0.13"
urlencoding = "2"
dirs = "5"
arboard = "3"

[dev-dependencies]
tempfile = "3"
